export default {
  '1': {
    chord_ID: '1',
    chord_HTML: 'I',
    interval: 0,
    inversion: 0,
    type: 'M',
    id: '0M0',
  },
  '2': {
    chord_ID: '2',
    chord_HTML: 'ii',
    interval: 2,
    inversion: 0,
    type: 'm',
    id: '2m0',
  },
  '3': {
    chord_ID: '3',
    chord_HTML: 'iii',
    interval: 4,
    inversion: 0,
    type: 'm',
    id: '4m0',
  },
  '4': {
    chord_ID: '4',
    chord_HTML: 'IV',
    interval: 5,
    inversion: 0,
    type: 'M',
    id: '5M0',
  },
  '5': {
    chord_ID: '5',
    chord_HTML: 'V',
    interval: 7,
    inversion: 0,
    type: 'M',
    id: '7M0',
  },
  '6': {
    chord_ID: '6',
    chord_HTML: 'vi',
    interval: 9,
    inversion: 0,
    type: 'm',
    id: '9m0',
  },
  '7': {
    chord_ID: '7',
    chord_HTML: 'vii&deg;',
    interval: 11,
    inversion: 0,
    type: 'd',
    id: '11d0',
  },
  '16': {
    chord_ID: '16',
    chord_HTML: 'I<sup>6</sup>',
    interval: 0,
    inversion: 1,
    type: 'M',
    id: '0M1',
  },
  '17': {
    chord_ID: '17',
    chord_HTML: 'I<sup>7</sup>',
    interval: 0,
    inversion: 0,
    type: 'M7',
    id: '0M70',
  },
  '26': {
    chord_ID: '26',
    chord_HTML: 'ii<sup>6</sup>',
    interval: 2,
    inversion: 1,
    type: 'm',
    id: '2m1',
  },
  '27': {
    chord_ID: '27',
    chord_HTML: 'ii<sup>7</sup>',
    interval: 2,
    inversion: 0,
    type: 'm7',
    id: '2m70',
  },
  '36': {
    chord_ID: '36',
    chord_HTML: 'iii<sup>6</sup>',
    interval: 4,
    inversion: 1,
    type: 'm',
    id: '4m1',
  },
  '37': {
    chord_ID: '37',
    chord_HTML: 'iii<sup>7</sup>',
    interval: 4,
    inversion: 0,
    type: 'm7',
    id: '4m70',
  },
  '46': {
    chord_ID: '46',
    chord_HTML: 'IV<sup>6</sup>',
    interval: 5,
    inversion: 1,
    type: 'M',
    id: '5M1',
  },
  '47': {
    chord_ID: '47',
    chord_HTML: 'IV<sup>7</sup>',
    interval: 5,
    inversion: 0,
    type: 'M7',
    id: '5M70',
  },
  '56': {
    chord_ID: '56',
    chord_HTML: 'V<sup>6</sup>',
    interval: 7,
    inversion: 1,
    type: 'M',
    id: '7M1',
  },
  '57': {
    chord_ID: '57',
    chord_HTML: 'V<sup>7</sup>',
    interval: 7,
    inversion: 0,
    type: 'D',
    id: '7D0',
  },
  '66': {
    chord_ID: '66',
    chord_HTML: 'vi<sup>6</sup>',
    interval: 9,
    inversion: 1,
    type: 'm',
    id: '9m1',
  },
  '67': {
    chord_ID: '67',
    chord_HTML: 'vi<sup>7</sup>',
    interval: 9,
    inversion: 0,
    type: 'm7',
    id: '9m70',
  },
  '76': {
    chord_ID: '76',
    chord_HTML: 'vii&deg;<sup>6</sup>',
    interval: 11,
    inversion: 1,
    type: 'd',
    id: '11d1',
  },
  '77': {
    chord_ID: '77',
    chord_HTML: 'vii<sup>??</sup><sup>7</sup>',
    interval: 11,
    inversion: 0,
    type: 'hd',
    id: '11hd0',
  },
  '142': {
    chord_ID: '142',
    chord_HTML: 'I<sup>4</sup><sub>2</sub>',
    interval: 0,
    inversion: 3,
    type: 'M7',
    id: '0M73',
  },
  '143': {
    chord_ID: '143',
    chord_HTML: 'I<sup>4</sup><sub>3</sub>',
    interval: 0,
    inversion: 2,
    type: 'M7',
    id: '0M72',
  },
  '164': {
    chord_ID: '164',
    chord_HTML: 'I<sup>6</sup><sub>4</sub>',
    interval: 0,
    inversion: 2,
    type: 'M',
    id: '0M2',
  },
  '165': {
    chord_ID: '165',
    chord_HTML: 'I<sup>6</sup><sub>5</sub>',
    interval: 0,
    inversion: 1,
    type: 'M7',
    id: '0M71',
  },
  '242': {
    chord_ID: '242',
    chord_HTML: 'ii<sup>4</sup><sub>2</sub>',
    interval: 2,
    inversion: 3,
    type: 'm7',
    id: '2m73',
  },
  '243': {
    chord_ID: '243',
    chord_HTML: 'ii<sup>4</sup><sub>3</sub>',
    interval: 2,
    inversion: 2,
    type: 'm7',
    id: '2m72',
  },
  '264': {
    chord_ID: '264',
    chord_HTML: 'ii<sup>6</sup><sub>4</sub>',
    interval: 2,
    inversion: 2,
    type: 'm',
    id: '2m2',
  },
  '265': {
    chord_ID: '265',
    chord_HTML: 'ii<sup>6</sup><sub>5</sub>',
    interval: 2,
    inversion: 1,
    type: 'm7',
    id: '2m71',
  },
  '342': {
    chord_ID: '342',
    chord_HTML: 'iii<sup>4</sup><sub>2</sub>',
    interval: 4,
    inversion: 3,
    type: 'm7',
    id: '4m73',
  },
  '343': {
    chord_ID: '343',
    chord_HTML: 'iii<sup>4</sup><sub>3</sub>',
    interval: 4,
    inversion: 2,
    type: 'm7',
    id: '4m72',
  },
  '364': {
    chord_ID: '364',
    chord_HTML: 'iii<sup>6</sup><sub>4</sub>',
    interval: 4,
    inversion: 2,
    type: 'm',
    id: '4m2',
  },
  '365': {
    chord_ID: '365',
    chord_HTML: 'iii<sup>6</sup><sub>5</sub>',
    interval: 4,
    inversion: 1,
    type: 'm7',
    id: '4m71',
  },
  '442': {
    chord_ID: '442',
    chord_HTML: 'IV<sup>4</sup><sub>2</sub>',
    interval: 5,
    inversion: 3,
    type: 'M7',
    id: '5M73',
  },
  '443': {
    chord_ID: '443',
    chord_HTML: 'IV<sup>4</sup><sub>3</sub>',
    interval: 5,
    inversion: 2,
    type: 'M7',
    id: '5M72',
  },
  '464': {
    chord_ID: '464',
    chord_HTML: 'IV<sup>6</sup><sub>4</sub>',
    interval: 5,
    inversion: 2,
    type: 'M',
    id: '5M2',
  },
  '465': {
    chord_ID: '465',
    chord_HTML: 'IV<sup>6</sup><sub>5</sub>',
    interval: 5,
    inversion: 1,
    type: 'M7',
    id: '5M71',
  },
  '542': {
    chord_ID: '542',
    chord_HTML: 'V<sup>4</sup><sub>2</sub>',
    interval: 7,
    inversion: 3,
    type: 'D',
    id: '7D3',
  },
  '543': {
    chord_ID: '543',
    chord_HTML: 'V<sup>4</sup><sub>3</sub>',
    interval: 7,
    inversion: 2,
    type: 'D',
    id: '7D2',
  },
  '564': {
    chord_ID: '564',
    chord_HTML: 'V<sup>6</sup><sub>4</sub>',
    interval: 7,
    inversion: 2,
    type: 'M',
    id: '7M2',
  },
  '565': {
    chord_ID: '565',
    chord_HTML: 'V<sup>6</sup><sub>5</sub>',
    interval: 7,
    inversion: 1,
    type: 'D',
    id: '7D1',
  },
  '642': {
    chord_ID: '642',
    chord_HTML: 'vi<sup>4</sup><sub>2</sub>',
    interval: 9,
    inversion: 3,
    type: 'm7',
    id: '9m73',
  },
  '643': {
    chord_ID: '643',
    chord_HTML: 'vi<sup>4</sup><sub>3</sub>',
    interval: 9,
    inversion: 2,
    type: 'm7',
    id: '9m72',
  },
  '664': {
    chord_ID: '664',
    chord_HTML: 'vi<sup>6</sup><sub>4</sub>',
    interval: 9,
    inversion: 2,
    type: 'm',
    id: '9m2',
  },
  '665': {
    chord_ID: '665',
    chord_HTML: 'vi<sup>6</sup><sub>5</sub>',
    interval: 9,
    inversion: 1,
    type: 'm7',
    id: '9m71',
  },
  b7: {
    chord_ID: 'b7',
    chord_HTML: '&#9837;VII',
    interval: 10,
    inversion: 0,
    type: 'M',
    id: '10M0',
  },
  '5/6': {
    chord_ID: '5/6',
    chord_HTML: 'V/vi',
    interval: 4,
    inversion: 0,
    type: 'M',
    id: '4M0',
  },
  '5/5': {
    chord_ID: '5/5',
    chord_HTML: 'V/V',
    interval: 2,
    inversion: 0,
    type: 'M',
    id: '2M0',
  },
  b3: {
    chord_ID: 'b3',
    chord_HTML: '&#9837;III',
    interval: 3,
    inversion: 0,
    type: 'M',
    id: '3M0',
  },
  '57/6': {
    chord_ID: '57/6',
    chord_HTML: 'V<sup>7</sup>/vi',
    interval: 4,
    inversion: 0,
    type: 'D',
    id: '4D0',
  },
  b6: {
    chord_ID: 'b6',
    chord_HTML: '&#9837;VI',
    interval: 8,
    inversion: 0,
    type: 'M',
    id: '8M0',
  },
  '57/4': {
    chord_ID: '57/4',
    chord_HTML: 'V<sup>7</sup>/IV',
    interval: 0,
    inversion: 0,
    type: 'D',
    id: '0D0',
  },
  b4: {
    chord_ID: 'b4',
    chord_HTML: 'iv',
    interval: 5,
    inversion: 0,
    type: 'm',
    id: '5m0',
  },
  L7: {
    chord_ID: 'L7',
    chord_HTML: 'vii',
    interval: 11,
    inversion: 0,
    type: 'm',
    id: '11m0',
  },
  '5/3': {
    chord_ID: '5/3',
    chord_HTML: 'V/iii',
    interval: 11,
    inversion: 0,
    type: 'M',
    id: '11M0',
  },
  '57/5': {
    chord_ID: '57/5',
    chord_HTML: 'V<sup>7</sup>/V',
    interval: 2,
    inversion: 0,
    type: 'D',
    id: '2D0',
  },
  '542/4': {
    chord_ID: '542/4',
    chord_HTML: 'V<sup>4</sup><sub>2</sub>/IV',
    interval: 0,
    inversion: 3,
    type: 'D',
    id: '0D3',
  },
  '7/2': {
    chord_ID: '7/2',
    chord_HTML: 'vii&deg;/ii',
    interval: 1,
    inversion: 0,
    type: 'd',
    id: '1d0',
  },
  '5/2': {
    chord_ID: '5/2',
    chord_HTML: 'V/ii',
    interval: 9,
    inversion: 0,
    type: 'M',
    id: '9M0',
  },
  M17: {
    chord_ID: 'M17',
    chord_HTML: 'Ib7',
    interval: 0,
    inversion: 0,
    type: 'D',
    id: '0D0',
  },
  b5: {
    chord_ID: 'b5',
    chord_HTML: 'v',
    interval: 7,
    inversion: 0,
    type: 'm',
    id: '7m0',
  },
  L27: {
    chord_ID: 'L27',
    chord_HTML: 'II<sup>7</sup>',
    interval: 1,
    inversion: 0,
    type: 'M7',
    id: '1M70',
  },
  M142: {
    chord_ID: 'M142',
    chord_HTML: 'I<sup>4</sup><sub>2</sub>',
    interval: 0,
    inversion: 3,
    type: 'M7',
    id: '0M73',
  },
  '564/6': {
    chord_ID: '564/6',
    chord_HTML: 'V<sup>6</sup><sub>4</sub>/vi',
    interval: 4,
    inversion: 2,
    type: 'M',
    id: '4M2',
  },
  L242: {
    chord_ID: 'L242',
    chord_HTML: 'II<sup>4</sup><sub>2</sub>',
    interval: 1,
    inversion: 3,
    type: 'M7',
    id: '1M73',
  },
  '7/5': {
    chord_ID: '7/5',
    chord_HTML: 'vii&deg;/V',
    interval: 6,
    inversion: 0,
    type: 'd',
    id: '6d0',
  },
  '7/6': {
    chord_ID: '7/6',
    chord_HTML: 'vii&deg;/vi',
    interval: 8,
    inversion: 0,
    type: 'd',
    id: '8d0',
  },
  '56/5': {
    chord_ID: '56/5',
    chord_HTML: 'V<sup>6</sup>/V',
    interval: 2,
    inversion: 1,
    type: 'M',
    id: '2M1',
  },
  '56/6': {
    chord_ID: '56/6',
    chord_HTML: 'V<sup>6</sup>/vi',
    interval: 4,
    inversion: 1,
    type: 'M',
    id: '4M1',
  },
  L4: {
    chord_ID: 'L4',
    chord_HTML: '&#9839;iv&deg;',
    interval: 6,
    inversion: 0,
    type: 'd',
    id: '6d0',
  },
  D3: {
    chord_ID: 'D3',
    chord_HTML: '&#9837;III',
    interval: 3,
    inversion: 0,
    type: 'M',
    id: '3M0',
  },
  b46: {
    chord_ID: 'b46',
    chord_HTML: 'iv<sup>6</sup>',
    interval: 5,
    inversion: 1,
    type: 'm',
    id: '5m1',
  },
  '464/4': {
    chord_ID: '464/4',
    chord_HTML: 'IV<sup>6</sup><sub>4</sub>/IV',
    interval: 10,
    inversion: 2,
    type: 'M',
    id: '10M2',
  },
  D47: {
    chord_ID: 'D47',
    chord_HTML: 'IVb7',
    interval: 5,
    inversion: 0,
    type: 'D',
    id: '5D0',
  },
  '565/6': {
    chord_ID: '565/6',
    chord_HTML: 'V<sup>6</sup><sub>5</sub>/vi',
    interval: 4,
    inversion: 1,
    type: 'D',
    id: '4D1',
  },
  '543/6': {
    chord_ID: '543/6',
    chord_HTML: 'V<sup>4</sup><sub>3</sub>/vi',
    interval: 4,
    inversion: 2,
    type: 'D',
    id: '4D2',
  },
  D6: {
    chord_ID: 'D6',
    chord_HTML: 'vi&deg;',
    interval: 9,
    inversion: 0,
    type: 'd',
    id: '9d0',
  },
  L26: {
    chord_ID: 'L26',
    chord_HTML: 'II<sup>6</sup>',
    interval: 1,
    inversion: 1,
    type: 'M',
    id: '1M1',
  },
  C5: {
    chord_ID: 'C5',
    chord_HTML: '&#9837;V',
    interval: 6,
    inversion: 0,
    type: 'M',
    id: '6M0',
  },
  b1: {
    chord_ID: 'b1',
    chord_HTML: 'i',
    interval: 0,
    inversion: 0,
    type: 'm',
    id: '0m0',
  },
  Y5: {
    chord_ID: 'Y5',
    chord_HTML: 'v&deg;',
    interval: 7,
    inversion: 0,
    type: 'd',
    id: '7d0',
  },
  Y4: {
    chord_ID: 'Y4',
    chord_HTML: 'iv',
    interval: 5,
    inversion: 0,
    type: 'm',
    id: '5m0',
  },
  '57/2': {
    chord_ID: '57/2',
    chord_HTML: 'V<sup>7</sup>/ii',
    interval: 9,
    inversion: 0,
    type: 'D',
    id: '9D0',
  },
  Y2: {
    chord_ID: 'Y2',
    chord_HTML: '&#9837;II',
    interval: 1,
    inversion: 0,
    type: 'M',
    id: '1M0',
  },
  '7/3': {
    chord_ID: '7/3',
    chord_HTML: 'vii&deg;/iii',
    interval: 3,
    inversion: 0,
    type: 'd',
    id: '3d0',
  },
  '56/2': {
    chord_ID: '56/2',
    chord_HTML: 'V<sup>6</sup>/ii',
    interval: 9,
    inversion: 1,
    type: 'M',
    id: '9M1',
  },
  '543/2': {
    chord_ID: '543/2',
    chord_HTML: 'V<sup>4</sup><sub>3</sub>/ii',
    interval: 9,
    inversion: 2,
    type: 'D',
    id: '9D2',
  },
  b2: {
    chord_ID: 'b2',
    chord_HTML: 'ii&deg;',
    interval: 2,
    inversion: 0,
    type: 'd',
    id: '2d0',
  },
  b77: {
    chord_ID: 'b77',
    chord_HTML: '&#9837;VIIb7',
    interval: 10,
    inversion: 0,
    type: 'D',
    id: '10D0',
  },
  '56/3': {
    chord_ID: '56/3',
    chord_HTML: 'V<sup>6</sup>/iii',
    interval: 11,
    inversion: 1,
    type: 'M',
    id: '11M1',
  },
  '4/3': {
    chord_ID: '4/3',
    chord_HTML: 'IV/iii',
    interval: 9,
    inversion: 0,
    type: 'M',
    id: '9M0',
  },
  b57: {
    chord_ID: 'b57',
    chord_HTML: 'v<sup>7</sup>',
    interval: 7,
    inversion: 0,
    type: 'm7',
    id: '7m70',
  },
  M5: {
    chord_ID: 'M5',
    chord_HTML: 'v',
    interval: 7,
    inversion: 0,
    type: 'm',
    id: '7m0',
  },
  '5/7': {
    chord_ID: '5/7',
    chord_HTML: 'V/vii',
    interval: 6,
    inversion: 0,
    type: 'M',
    id: '6M0',
  },
  Y3: {
    chord_ID: 'Y3',
    chord_HTML: '&#9837;III',
    interval: 3,
    inversion: 0,
    type: 'M',
    id: '3M0',
  },
  b27: {
    chord_ID: 'b27',
    chord_HTML: 'ii<sup>??</sup><sup>7</sup>',
    interval: 2,
    inversion: 0,
    type: 'hd',
    id: '2hd0',
  },
  b165: {
    chord_ID: 'b165',
    chord_HTML: 'i<sup>6</sup><sub>5</sub>',
    interval: 0,
    inversion: 1,
    type: 'm7',
    id: '0m71',
  },
  Y27: {
    chord_ID: 'Y27',
    chord_HTML: '&#9837;II<sup>7</sup>',
    interval: 1,
    inversion: 0,
    type: 'M7',
    id: '1M70',
  },
  M57: {
    chord_ID: 'M57',
    chord_HTML: 'v<sup>7</sup>',
    interval: 7,
    inversion: 0,
    type: 'm7',
    id: '7m70',
  },
  b47: {
    chord_ID: 'b47',
    chord_HTML: 'iv<sup>7</sup>',
    interval: 5,
    inversion: 0,
    type: 'm7',
    id: '5m70',
  },
  L77: {
    chord_ID: 'L77',
    chord_HTML: 'vii<sup>7</sup>',
    interval: 11,
    inversion: 0,
    type: 'm7',
    id: '11m70',
  },
  '47/4': {
    chord_ID: '47/4',
    chord_HTML: 'IV<sup>7</sup>/IV',
    interval: 10,
    inversion: 0,
    type: 'M7',
    id: '10M70',
  },
  b465: {
    chord_ID: 'b465',
    chord_HTML: 'iv<sup>6</sup><sub>5</sub>',
    interval: 5,
    inversion: 1,
    type: 'm7',
    id: '5m71',
  },
  b67: {
    chord_ID: 'b67',
    chord_HTML: '&#9837;VI<sup>7</sup>',
    interval: 8,
    inversion: 0,
    type: 'M7',
    id: '8M70',
  },
  D17: {
    chord_ID: 'D17',
    chord_HTML: 'i<sup>7</sup>',
    interval: 0,
    inversion: 0,
    type: 'm7',
    id: '0m70',
  },
  L264: {
    chord_ID: 'L264',
    chord_HTML: 'II<sup>6</sup><sub>4</sub>',
    interval: 1,
    inversion: 2,
    type: 'M',
    id: '1M2',
  },
  b16: {
    chord_ID: 'b16',
    chord_HTML: 'i<sup>6</sup>',
    interval: 0,
    inversion: 1,
    type: 'm',
    id: '0m1',
  },
  L265: {
    chord_ID: 'L265',
    chord_HTML: 'II<sup>6</sup><sub>5</sub>',
    interval: 1,
    inversion: 1,
    type: 'M7',
    id: '1M71',
  },
  C16: {
    chord_ID: 'C16',
    chord_HTML: 'i&deg;<sup>6</sup>',
    interval: 0,
    inversion: 1,
    type: 'd',
    id: '0d1',
  },
  '57/7': {
    chord_ID: '57/7',
    chord_HTML: 'V<sup>7</sup>/vii',
    interval: 6,
    inversion: 0,
    type: 'D',
    id: '6D0',
  },
  D442: {
    chord_ID: 'D442',
    chord_HTML: 'IV<sup>4</sup><sub>2</sub>',
    interval: 5,
    inversion: 3,
    type: 'M7',
    id: '5M73',
  },
  '77/5': {
    chord_ID: '77/5',
    chord_HTML: 'vii<sup>??</sup><sup>7</sup>/V',
    interval: 6,
    inversion: 0,
    type: 'hd',
    id: '6hd0',
  },
  D16: {
    chord_ID: 'D16',
    chord_HTML: 'i<sup>6</sup>',
    interval: 0,
    inversion: 1,
    type: 'm',
    id: '0m1',
  },
  '542/6': {
    chord_ID: '542/6',
    chord_HTML: 'V<sup>4</sup><sub>2</sub>/vi',
    interval: 4,
    inversion: 3,
    type: 'D',
    id: '4D3',
  },
  '565/2': {
    chord_ID: '565/2',
    chord_HTML: 'V<sup>6</sup><sub>5</sub>/ii',
    interval: 9,
    inversion: 1,
    type: 'D',
    id: '9D1',
  },
  '47/7': {
    chord_ID: '47/7',
    chord_HTML: 'IV<sup>7</sup>/vii',
    interval: 4,
    inversion: 0,
    type: 'M7',
    id: '4M70',
  },
  L765: {
    chord_ID: 'L765',
    chord_HTML: 'vii<sup>6</sup><sub>5</sub>',
    interval: 11,
    inversion: 1,
    type: 'm7',
    id: '11m71',
  },
  M37: {
    chord_ID: 'M37',
    chord_HTML: 'iii<sup>??</sup><sup>7</sup>',
    interval: 4,
    inversion: 0,
    type: 'hd',
    id: '4hd0',
  },
  b37: {
    chord_ID: 'b37',
    chord_HTML: '&#9837;III<sup>7</sup>',
    interval: 3,
    inversion: 0,
    type: 'M7',
    id: '3M70',
  },
  C37: {
    chord_ID: 'C37',
    chord_HTML: '&#9837;iii<sup>7</sup>',
    interval: 3,
    inversion: 0,
    type: 'm7',
    id: '3m70',
  },
  D37: {
    chord_ID: 'D37',
    chord_HTML: '&#9837;III<sup>7</sup>',
    interval: 3,
    inversion: 0,
    type: 'M7',
    id: '3M70',
  },
  Y37: {
    chord_ID: 'Y37',
    chord_HTML: '&#9837;IIIb7',
    interval: 3,
    inversion: 0,
    type: 'D',
    id: '3D0',
  },
  '565/5': {
    chord_ID: '565/5',
    chord_HTML: 'V<sup>6</sup><sub>5</sub>/V',
    interval: 2,
    inversion: 1,
    type: 'D',
    id: '2D1',
  },
  M67: {
    chord_ID: 'M67',
    chord_HTML: 'vi<sup>7</sup>',
    interval: 9,
    inversion: 0,
    type: 'm7',
    id: '9m70',
  },
  C164: {
    chord_ID: 'C164',
    chord_HTML: 'i&deg;<sup>6</sup><sub>4</sub>',
    interval: 0,
    inversion: 2,
    type: 'd',
    id: '0d2',
  },
  Y57: {
    chord_ID: 'Y57',
    chord_HTML: 'v<sup>??</sup><sup>7</sup>',
    interval: 7,
    inversion: 0,
    type: 'hd',
    id: '7hd0',
  },
  M77: {
    chord_ID: 'M77',
    chord_HTML: '&#9837;VII<sup>7</sup>',
    interval: 10,
    inversion: 0,
    type: 'M7',
    id: '10M70',
  },
  D5: {
    chord_ID: 'D5',
    chord_HTML: 'v',
    interval: 7,
    inversion: 0,
    type: 'm',
    id: '7m0',
  },
  M1: {
    chord_ID: 'M1',
    chord_HTML: 'I',
    interval: 0,
    inversion: 0,
    type: 'M',
    id: '0M0',
  },
  D4: {
    chord_ID: 'D4',
    chord_HTML: 'IV',
    interval: 5,
    inversion: 0,
    type: 'M',
    id: '5M0',
  },
  b17: {
    chord_ID: 'b17',
    chord_HTML: 'i<sup>7</sup>',
    interval: 0,
    inversion: 0,
    type: 'm7',
    id: '0m70',
  },
  D77: {
    chord_ID: 'D77',
    chord_HTML: '&#9837;VII<sup>7</sup>',
    interval: 10,
    inversion: 0,
    type: 'M7',
    id: '10M70',
  },
  '57/3': {
    chord_ID: '57/3',
    chord_HTML: 'V<sup>7</sup>/iii',
    interval: 11,
    inversion: 0,
    type: 'D',
    id: '11D0',
  },
  '47/3': {
    chord_ID: '47/3',
    chord_HTML: 'IV<sup>7</sup>/iii',
    interval: 9,
    inversion: 0,
    type: 'M7',
    id: '9M70',
  },
  L5: {
    chord_ID: 'L5',
    chord_HTML: 'V',
    interval: 7,
    inversion: 0,
    type: 'M',
    id: '7M0',
  },
  L1: {
    chord_ID: 'L1',
    chord_HTML: 'I',
    interval: 0,
    inversion: 0,
    type: 'M',
    id: '0M0',
  },
  '542/5': {
    chord_ID: '542/5',
    chord_HTML: 'V<sup>4</sup><sub>2</sub>/V',
    interval: 2,
    inversion: 3,
    type: 'D',
    id: '2D3',
  },
  '565/3': {
    chord_ID: '565/3',
    chord_HTML: 'V<sup>6</sup><sub>5</sub>/iii',
    interval: 11,
    inversion: 1,
    type: 'D',
    id: '11D1',
  },
  L6: {
    chord_ID: 'L6',
    chord_HTML: 'vi',
    interval: 9,
    inversion: 0,
    type: 'm',
    id: '9m0',
  },
  C2: {
    chord_ID: 'C2',
    chord_HTML: '&#9837;II',
    interval: 1,
    inversion: 0,
    type: 'M',
    id: '1M0',
  },
  '464/5': {
    chord_ID: '464/5',
    chord_HTML: 'IV<sup>6</sup><sub>4</sub>/V',
    interval: 0,
    inversion: 2,
    type: 'M',
    id: '0M2',
  },
  M66: {
    chord_ID: 'M66',
    chord_HTML: 'vi<sup>6</sup>',
    interval: 9,
    inversion: 1,
    type: 'm',
    id: '9m1',
  },
  b464: {
    chord_ID: 'b464',
    chord_HTML: 'iv<sup>6</sup><sub>4</sub>',
    interval: 5,
    inversion: 2,
    type: 'm',
    id: '5m2',
  },
  C464: {
    chord_ID: 'C464',
    chord_HTML: 'iv<sup>6</sup><sub>4</sub>',
    interval: 5,
    inversion: 2,
    type: 'm',
    id: '5m2',
  },
  '46/4': {
    chord_ID: '46/4',
    chord_HTML: 'IV<sup>6</sup>/IV',
    interval: 10,
    inversion: 1,
    type: 'M',
    id: '10M1',
  },
  M4: {
    chord_ID: 'M4',
    chord_HTML: 'IV',
    interval: 5,
    inversion: 0,
    type: 'M',
    id: '5M0',
  },
  L46: {
    chord_ID: 'L46',
    chord_HTML: '&#9839;iv&deg;<sup>6</sup>',
    interval: 6,
    inversion: 1,
    type: 'd',
    id: '6d1',
  },
  C67: {
    chord_ID: 'C67',
    chord_HTML: '&#9837;VIb7',
    interval: 8,
    inversion: 0,
    type: 'D',
    id: '8D0',
  },
  C465: {
    chord_ID: 'C465',
    chord_HTML: 'iv<sup>6</sup><sub>5</sub>',
    interval: 5,
    inversion: 1,
    type: 'm7',
    id: '5m71',
  },
  '76/5': {
    chord_ID: '76/5',
    chord_HTML: 'vii&deg;<sup>6</sup>/V',
    interval: 6,
    inversion: 1,
    type: 'd',
    id: '6d1',
  },
  '542/2': {
    chord_ID: '542/2',
    chord_HTML: 'V<sup>4</sup><sub>2</sub>/ii',
    interval: 9,
    inversion: 3,
    type: 'D',
    id: '9D3',
  },
  '542/3': {
    chord_ID: '542/3',
    chord_HTML: 'V<sup>4</sup><sub>2</sub>/iii',
    interval: 11,
    inversion: 3,
    type: 'D',
    id: '11D3',
  },
  '564/4': {
    chord_ID: '564/4',
    chord_HTML: 'V<sup>6</sup><sub>4</sub>/IV',
    interval: 0,
    inversion: 2,
    type: 'M',
    id: '0M2',
  },
  M76: {
    chord_ID: 'M76',
    chord_HTML: '&#9837;VII<sup>6</sup>',
    interval: 10,
    inversion: 1,
    type: 'M',
    id: '10M1',
  },
  '76/6': {
    chord_ID: '76/6',
    chord_HTML: 'vii&deg;<sup>6</sup>/vi',
    interval: 8,
    inversion: 1,
    type: 'd',
    id: '8d1',
  },
  D464: {
    chord_ID: 'D464',
    chord_HTML: 'IV<sup>6</sup><sub>4</sub>',
    interval: 5,
    inversion: 2,
    type: 'M',
    id: '5M2',
  },
  b564: {
    chord_ID: 'b564',
    chord_HTML: 'v<sup>6</sup><sub>4</sub>',
    interval: 7,
    inversion: 2,
    type: 'm',
    id: '7m2',
  },
  Y66: {
    chord_ID: 'Y66',
    chord_HTML: '&#9837;VI<sup>6</sup>',
    interval: 8,
    inversion: 1,
    type: 'M',
    id: '8M1',
  },
  C3: {
    chord_ID: 'C3',
    chord_HTML: '&#9837;iii',
    interval: 3,
    inversion: 0,
    type: 'm',
    id: '3m0',
  },
  '46/6': {
    chord_ID: '46/6',
    chord_HTML: 'IV<sup>6</sup>/vi',
    interval: 2,
    inversion: 1,
    type: 'M',
    id: '2M1',
  },
  '564/3': {
    chord_ID: '564/3',
    chord_HTML: 'V<sup>6</sup><sub>4</sub>/iii',
    interval: 11,
    inversion: 2,
    type: 'M',
    id: '11M2',
  },
  C4: {
    chord_ID: 'C4',
    chord_HTML: 'iv',
    interval: 5,
    inversion: 0,
    type: 'm',
    id: '5m0',
  },
  L764: {
    chord_ID: 'L764',
    chord_HTML: 'vii<sup>6</sup><sub>4</sub>',
    interval: 11,
    inversion: 2,
    type: 'm',
    id: '11m2',
  },
  '564/2': {
    chord_ID: '564/2',
    chord_HTML: 'V<sup>6</sup><sub>4</sub>/ii',
    interval: 9,
    inversion: 2,
    type: 'M',
    id: '9M2',
  },
  '76/2': {
    chord_ID: '76/2',
    chord_HTML: 'vii&deg;<sup>6</sup>/ii',
    interval: 1,
    inversion: 1,
    type: 'd',
    id: '1d1',
  },
  L564: {
    chord_ID: 'L564',
    chord_HTML: 'V<sup>6</sup><sub>4</sub>',
    interval: 7,
    inversion: 2,
    type: 'M',
    id: '7M2',
  },
  '543/3': {
    chord_ID: '543/3',
    chord_HTML: 'V<sup>4</sup><sub>3</sub>/iii',
    interval: 11,
    inversion: 2,
    type: 'D',
    id: '11D2',
  },
  C1: {
    chord_ID: 'C1',
    chord_HTML: 'i&deg;',
    interval: 0,
    inversion: 0,
    type: 'd',
    id: '0d0',
  },
  M36: {
    chord_ID: 'M36',
    chord_HTML: 'iii&deg;<sup>6</sup>',
    interval: 4,
    inversion: 1,
    type: 'd',
    id: '4d1',
  },
  '543/4': {
    chord_ID: '543/4',
    chord_HTML: 'V<sup>4</sup><sub>3</sub>/IV',
    interval: 0,
    inversion: 2,
    type: 'D',
    id: '0D2',
  },
  M143: {
    chord_ID: 'M143',
    chord_HTML: 'I<sup>4</sup><sub>3</sub>',
    interval: 0,
    inversion: 2,
    type: 'M7',
    id: '0M72',
  },
  b56: {
    chord_ID: 'b56',
    chord_HTML: 'v<sup>6</sup>',
    interval: 7,
    inversion: 1,
    type: 'm',
    id: '7m1',
  },
  b26: {
    chord_ID: 'b26',
    chord_HTML: 'ii&deg;<sup>6</sup>',
    interval: 2,
    inversion: 1,
    type: 'd',
    id: '2d1',
  },
  b565: {
    chord_ID: 'b565',
    chord_HTML: 'v<sup>6</sup><sub>5</sub>',
    interval: 7,
    inversion: 1,
    type: 'm7',
    id: '7m71',
  },
  C6: {
    chord_ID: 'C6',
    chord_HTML: '&#9837;VI',
    interval: 8,
    inversion: 0,
    type: 'M',
    id: '8M0',
  },
  Y7: {
    chord_ID: 'Y7',
    chord_HTML: '&#9837;vii',
    interval: 10,
    inversion: 0,
    type: 'm',
    id: '10m0',
  },
  C57: {
    chord_ID: 'C57',
    chord_HTML: '&#9837;V<sup>7</sup>',
    interval: 6,
    inversion: 0,
    type: 'D',
    id: '6D0',
  },
  D142: {
    chord_ID: 'D142',
    chord_HTML: 'i<sup>4</sup><sub>2</sub>',
    interval: 0,
    inversion: 3,
    type: 'm7',
    id: '0m73',
  },
  M3: {
    chord_ID: 'M3',
    chord_HTML: 'iii&deg;',
    interval: 4,
    inversion: 0,
    type: 'd',
    id: '4d0',
  },
  D565: {
    chord_ID: 'D565',
    chord_HTML: 'v<sup>6</sup><sub>5</sub>',
    interval: 7,
    inversion: 1,
    type: 'm7',
    id: '7m71',
  },
  b442: {
    chord_ID: 'b442',
    chord_HTML: 'iv<sup>4</sup><sub>2</sub>',
    interval: 5,
    inversion: 3,
    type: 'm7',
    id: '5m73',
  },
  b36: {
    chord_ID: 'b36',
    chord_HTML: '&#9837;III<sup>6</sup>',
    interval: 3,
    inversion: 1,
    type: 'M',
    id: '3M1',
  },
  Y77: {
    chord_ID: 'Y77',
    chord_HTML: '&#9837;vii<sup>7</sup>',
    interval: 10,
    inversion: 0,
    type: 'm7',
    id: '10m70',
  },
  b164: {
    chord_ID: 'b164',
    chord_HTML: 'i<sup>6</sup><sub>4</sub>',
    interval: 0,
    inversion: 2,
    type: 'm',
    id: '0m2',
  },
  L57: {
    chord_ID: 'L57',
    chord_HTML: 'V#7',
    interval: 7,
    inversion: 0,
    type: 'M7',
    id: '7M70',
  },
  '543/5': {
    chord_ID: '543/5',
    chord_HTML: 'V<sup>4</sup><sub>3</sub>/V',
    interval: 2,
    inversion: 2,
    type: 'D',
    id: '2D2',
  },
  '7/7': {
    chord_ID: '7/7',
    chord_HTML: 'vii&deg;/vii',
    interval: 10,
    inversion: 0,
    type: 'd',
    id: '10d0',
  },
  b76: {
    chord_ID: 'b76',
    chord_HTML: '&#9837;VII<sup>6</sup>',
    interval: 10,
    inversion: 1,
    type: 'M',
    id: '10M1',
  },
  L3: {
    chord_ID: 'L3',
    chord_HTML: 'iii',
    interval: 4,
    inversion: 0,
    type: 'm',
    id: '4m0',
  },
  '76/3': {
    chord_ID: '76/3',
    chord_HTML: 'vii&deg;<sup>6</sup>/iii',
    interval: 3,
    inversion: 1,
    type: 'd',
    id: '3d1',
  },
  D2: {
    chord_ID: 'D2',
    chord_HTML: 'ii',
    interval: 2,
    inversion: 0,
    type: 'm',
    id: '2m0',
  },
  '564/5': {
    chord_ID: '564/5',
    chord_HTML: 'V<sup>6</sup><sub>4</sub>/V',
    interval: 2,
    inversion: 2,
    type: 'M',
    id: '2M2',
  },
  '47/2': {
    chord_ID: '47/2',
    chord_HTML: 'IV<sup>7</sup>/ii',
    interval: 7,
    inversion: 0,
    type: 'M7',
    id: '7M70',
  },
  '4/2': {
    chord_ID: '4/2',
    chord_HTML: 'IV/ii',
    interval: 7,
    inversion: 0,
    type: 'M',
    id: '7M0',
  },
  L742: {
    chord_ID: 'L742',
    chord_HTML: 'vii<sup>4</sup><sub>2</sub>',
    interval: 11,
    inversion: 3,
    type: 'm7',
    id: '11m73',
  },
  M27: {
    chord_ID: 'M27',
    chord_HTML: 'ii<sup>7</sup>',
    interval: 2,
    inversion: 0,
    type: 'm7',
    id: '2m70',
  },
  D67: {
    chord_ID: 'D67',
    chord_HTML: 'vi<sup>??</sup><sup>7</sup>',
    interval: 9,
    inversion: 0,
    type: 'hd',
    id: '9hd0',
  },
  '4/7': {
    chord_ID: '4/7',
    chord_HTML: 'IV/vii',
    interval: 4,
    inversion: 0,
    type: 'M',
    id: '4M0',
  },
  b66: {
    chord_ID: 'b66',
    chord_HTML: '&#9837;VI<sup>6</sup>',
    interval: 8,
    inversion: 1,
    type: 'M',
    id: '8M1',
  },
  M565: {
    chord_ID: 'M565',
    chord_HTML: 'v<sup>6</sup><sub>5</sub>',
    interval: 7,
    inversion: 1,
    type: 'm7',
    id: '7m71',
  },
  M443: {
    chord_ID: 'M443',
    chord_HTML: 'IV<sup>4</sup><sub>3</sub>',
    interval: 5,
    inversion: 2,
    type: 'M7',
    id: '5M72',
  },
};
